local addonName, Wise = ...

function Wise:GetDemoBarGroup()
    local demoGroup = {
        isWiser = false,
        type = "line",
        lineOrientation = "horizontal",
        dynamic = false,
        anchor = {point = "CENTER", x = 0, y = 0},
        visibilitySettings = { customShow = "[always]" },
        keybindSettings = {},
        actions = {
            [1] = {
                conflictStrategy = "sequence",
                { type = "action", value = 133, name = "Override Bar Button 1", conditions = "[overridebar]", category = "global", exclusive = true },
                { type = "action", value = 145, name = "Possess Bar Button 1", conditions = "[possessbar]", category = "global", exclusive = true },
                { type = "spell", value = "Surge Forward", conditions = "[flying]", category = "global", exclusive = true },
                { type = "spell", value = "Shield Wall", category = "spec", classRestriction = "WARRIOR", addedByClass = "WARRIOR", specRestriction = 73, addedBySpec = 73 },
                { type = "spell", value = "Die by the Sword", category = "class", classRestriction = "WARRIOR", addedByClass = "WARRIOR" },
                { type = "spell", value = "Enraged Regeneration", category = "spec", classRestriction = "WARRIOR", addedByClass = "WARRIOR", specRestriction = 72, addedBySpec = 72 },
                { type = "spell", value = "Rallying Cry", category = "class", classRestriction = "WARRIOR", addedByClass = "WARRIOR" },
                { type = "spell", value = "Spell Reflection", category = "class", classRestriction = "WARRIOR", addedByClass = "WARRIOR" },
                { type = "spell", value = "Ignore Pain", category = "spec", classRestriction = "WARRIOR", addedByClass = "WARRIOR", specRestriction = 73, addedBySpec = 73 },
                { type = "spell", value = "Divine Shield", category = "class", classRestriction = "PALADIN", addedByClass = "PALADIN" },
                { type = "spell", value = "Ardent Defender", category = "spec", classRestriction = "PALADIN", addedByClass = "PALADIN", specRestriction = 66, addedBySpec = 66 },
                { type = "spell", value = "Guardian of Ancient Kings", category = "spec", classRestriction = "PALADIN", addedByClass = "PALADIN", specRestriction = 66, addedBySpec = 66 },
                { type = "spell", value = "Lay on Hands", category = "class", classRestriction = "PALADIN", addedByClass = "PALADIN" },
                { type = "spell", value = "Aura Mastery", category = "spec", classRestriction = "PALADIN", addedByClass = "PALADIN", specRestriction = 65, addedBySpec = 65 },
                { type = "spell", value = "Blessing of Protection", category = "class", classRestriction = "PALADIN", addedByClass = "PALADIN" },
                { type = "spell", value = "Divine Protection", category = "class", classRestriction = "PALADIN", addedByClass = "PALADIN" },
                { type = "spell", value = "Aspect of the Turtle", category = "class", classRestriction = "HUNTER", addedByClass = "HUNTER" },
                { type = "spell", value = "Survival of the Fittest", category = "class", classRestriction = "HUNTER", addedByClass = "HUNTER" },
                { type = "spell", value = "Exhilaration", category = "class", classRestriction = "HUNTER", addedByClass = "HUNTER" },
                { type = "spell", value = "Evasion", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Cloak of Shadows", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Crimson Vial", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Vanish", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Feint", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Pain Suppression", category = "spec", classRestriction = "PRIEST", addedByClass = "PRIEST", specRestriction = 256, addedBySpec = 256 },
                { type = "spell", value = "Guardian Spirit", category = "spec", classRestriction = "PRIEST", addedByClass = "PRIEST", specRestriction = 257, addedBySpec = 257 },
                { type = "spell", value = "Desperate Prayer", category = "class", classRestriction = "PRIEST", addedByClass = "PRIEST" },
                { type = "spell", value = "Power Word: Barrier", category = "spec", classRestriction = "PRIEST", addedByClass = "PRIEST", specRestriction = 256, addedBySpec = 256 },
                { type = "spell", value = "Divine Hymn", category = "spec", classRestriction = "PRIEST", addedByClass = "PRIEST", specRestriction = 257, addedBySpec = 257 },
                { type = "spell", value = "Dispersion", category = "spec", classRestriction = "PRIEST", addedByClass = "PRIEST", specRestriction = 258, addedBySpec = 258 },
                { type = "spell", value = "Vampiric Embrace", category = "spec", classRestriction = "PRIEST", addedByClass = "PRIEST", specRestriction = 258, addedBySpec = 258 },
                { type = "spell", value = "Power Word: Life", category = "class", classRestriction = "PRIEST", addedByClass = "PRIEST" },
                { type = "spell", value = "Icebound Fortitude", category = "class", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT" },
                { type = "spell", value = "Anti-Magic Shell", category = "class", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT" },
                { type = "spell", value = "Vampiric Blood", category = "spec", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT", specRestriction = 250, addedBySpec = 250 },
                { type = "spell", value = "Dancing Rune Weapon", category = "spec", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT", specRestriction = 250, addedBySpec = 250 },
                { type = "spell", value = "Anti-Magic Zone", category = "class", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT" },
                { type = "spell", value = "Lichborne", category = "class", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT" },
                { type = "spell", value = "Astral Shift", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Spirit Link Totem", category = "spec", classRestriction = "SHAMAN", addedByClass = "SHAMAN", specRestriction = 264, addedBySpec = 264 },
                { type = "spell", value = "Healing Tide Totem", category = "spec", classRestriction = "SHAMAN", addedByClass = "SHAMAN", specRestriction = 264, addedBySpec = 264 },
                { type = "spell", value = "Ancestral Guidance", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Earth Elemental", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Ice Block", category = "class", classRestriction = "MAGE", addedByClass = "MAGE" },
                { type = "spell", value = "Greater Invisibility", category = "class", classRestriction = "MAGE", addedByClass = "MAGE" },
                { type = "spell", value = "Alter Time", category = "class", classRestriction = "MAGE", addedByClass = "MAGE" },
                { type = "spell", value = "Prismatic Barrier", category = "spec", classRestriction = "MAGE", addedByClass = "MAGE", specRestriction = 62, addedBySpec = 62 },
                { type = "spell", value = "Blazing Barrier", category = "spec", classRestriction = "MAGE", addedByClass = "MAGE", specRestriction = 63, addedBySpec = 63 },
                { type = "spell", value = "Ice Barrier", category = "spec", classRestriction = "MAGE", addedByClass = "MAGE", specRestriction = 64, addedBySpec = 64 },
                { type = "spell", value = "Mass Barrier", category = "class", classRestriction = "MAGE", addedByClass = "MAGE" },
                { type = "spell", value = "Unending Resolve", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Dark Pact", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Mortal Coil", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Fortifying Brew", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Diffuse Magic", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Dampen Harm", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Revival", category = "spec", classRestriction = "MONK", addedByClass = "MONK", specRestriction = 270, addedBySpec = 270 },
                { type = "spell", value = "Life Cocoon", category = "spec", classRestriction = "MONK", addedByClass = "MONK", specRestriction = 270, addedBySpec = 270 },
                { type = "spell", value = "Zen Meditation", category = "spec", classRestriction = "MONK", addedByClass = "MONK", specRestriction = 268, addedBySpec = 268 },
                { type = "spell", value = "Touch of Karma", category = "spec", classRestriction = "MONK", addedByClass = "MONK", specRestriction = 269, addedBySpec = 269 },
                { type = "spell", value = "Survival Instincts", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Barkskin", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Frenzied Regeneration", category = "spec", classRestriction = "DRUID", addedByClass = "DRUID", specRestriction = 104, addedBySpec = 104 },
                { type = "spell", value = "Tranquility", category = "spec", classRestriction = "DRUID", addedByClass = "DRUID", specRestriction = 105, addedBySpec = 105 },
                { type = "spell", value = "Ironbark", category = "spec", classRestriction = "DRUID", addedByClass = "DRUID", specRestriction = 105, addedBySpec = 105 },
                { type = "spell", value = "Renewal", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Blur", category = "spec", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER", specRestriction = 577, addedBySpec = 577 },
                { type = "spell", value = "Netherwalk", category = "spec", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER", specRestriction = 577, addedBySpec = 577 },
                { type = "spell", value = "Metamorphosis", category = "spec", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER", specRestriction = 581, addedBySpec = 581 },
                { type = "spell", value = "Fiery Brand", category = "spec", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER", specRestriction = 581, addedBySpec = 581 },
                { type = "spell", value = "Obsidian Scales", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
                { type = "spell", value = "Renewing Blaze", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
                { type = "spell", value = "Rewind", category = "spec", classRestriction = "EVOKER", addedByClass = "EVOKER", specRestriction = 1468, addedBySpec = 1468 },
                { type = "spell", value = "Emerald Communion", category = "spec", classRestriction = "EVOKER", addedByClass = "EVOKER", specRestriction = 1468, addedBySpec = 1468 },
                { type = "spell", value = "Zephyr", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
            },
            [2] = {
                conflictStrategy = "sequence",
                { type = "action", value = 134, name = "Override Bar Button 2", conditions = "[overridebar]", category = "global", exclusive = true },
                { type = "action", value = 146, name = "Possess Bar Button 2", conditions = "[possessbar]", category = "global", exclusive = true },
                { type = "spell", value = "Skyward Ascent", conditions = "[flying]", category = "global", exclusive = true },
                { type = "spell", value = "Pummel", category = "class", classRestriction = "WARRIOR", addedByClass = "WARRIOR" },
                { type = "spell", value = "Rebuke", category = "class", classRestriction = "PALADIN", addedByClass = "PALADIN" },
                { type = "spell", value = "Counter Shot", category = "spec", classRestriction = "HUNTER", addedByClass = "HUNTER", specRestriction = 253, addedBySpec = 253 },
                { type = "spell", value = "Counter Shot", category = "spec", classRestriction = "HUNTER", addedByClass = "HUNTER", specRestriction = 254, addedBySpec = 254 },
                { type = "spell", value = "Muzzle", category = "spec", classRestriction = "HUNTER", addedByClass = "HUNTER", specRestriction = 255, addedBySpec = 255 },
                { type = "spell", value = "Kick", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Silence", category = "spec", classRestriction = "PRIEST", addedByClass = "PRIEST", specRestriction = 258, addedBySpec = 258 },
                { type = "spell", value = "Mind Freeze", category = "class", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT" },
                { type = "spell", value = "Wind Shear", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Counterspell", category = "class", classRestriction = "MAGE", addedByClass = "MAGE" },
                { type = "spell", value = "Spell Lock", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Spear Hand Strike", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Skull Bash", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Solar Beam", category = "spec", classRestriction = "DRUID", addedByClass = "DRUID", specRestriction = 102, addedBySpec = 102 },
                { type = "spell", value = "Disrupt", category = "class", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER" },
                { type = "spell", value = "Quell", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
            },
            [3] = {
                conflictStrategy = "sequence",
                { type = "action", value = 135, name = "Override Bar Button 3", conditions = "[overridebar]", category = "global", exclusive = true },
                { type = "action", value = 147, name = "Possess Bar Button 3", conditions = "[possessbar]", category = "global", exclusive = true },
                { type = "spell", value = "Whirling Surge", conditions = "[flying]", category = "global", exclusive = true },
                { type = "spell", value = "Taunt", category = "class", classRestriction = "WARRIOR", addedByClass = "WARRIOR" },
                { type = "spell", value = "Avatar", category = "class", classRestriction = "WARRIOR", addedByClass = "WARRIOR" },
                { type = "spell", value = "Recklessness", category = "spec", classRestriction = "WARRIOR", addedByClass = "WARRIOR", specRestriction = 72, addedBySpec = 72 },
                { type = "spell", value = "Colossus Smash", category = "spec", classRestriction = "WARRIOR", addedByClass = "WARRIOR", specRestriction = 71, addedBySpec = 71 },
                { type = "spell", value = "Warbreaker", category = "spec", classRestriction = "WARRIOR", addedByClass = "WARRIOR", specRestriction = 71, addedBySpec = 71 },
                { type = "spell", value = "Sweeping Strikes", category = "spec", classRestriction = "WARRIOR", addedByClass = "WARRIOR", specRestriction = 71, addedBySpec = 71 },
                { type = "spell", value = "Hand of Reckoning", category = "class", classRestriction = "PALADIN", addedByClass = "PALADIN" },
                { type = "spell", value = "Avenging Wrath", category = "class", classRestriction = "PALADIN", addedByClass = "PALADIN" },
                { type = "spell", value = "Crusade", category = "spec", classRestriction = "PALADIN", addedByClass = "PALADIN", specRestriction = 70, addedBySpec = 70 },
                { type = "spell", value = "Sentinel", category = "spec", classRestriction = "PALADIN", addedByClass = "PALADIN", specRestriction = 66, addedBySpec = 66 },
                { type = "spell", value = "Bestial Wrath", category = "spec", classRestriction = "HUNTER", addedByClass = "HUNTER", specRestriction = 253, addedBySpec = 253 },
                { type = "spell", value = "Trueshot", category = "spec", classRestriction = "HUNTER", addedByClass = "HUNTER", specRestriction = 254, addedBySpec = 254 },
                { type = "spell", value = "Coordinated Assault", category = "spec", classRestriction = "HUNTER", addedByClass = "HUNTER", specRestriction = 255, addedBySpec = 255 },
                { type = "spell", value = "Call of the Wild", category = "class", classRestriction = "HUNTER", addedByClass = "HUNTER" },
                { type = "spell", value = "Adrenaline Rush", category = "spec", classRestriction = "ROGUE", addedByClass = "ROGUE", specRestriction = 260, addedBySpec = 260 },
                { type = "spell", value = "Shadow Dance", category = "spec", classRestriction = "ROGUE", addedByClass = "ROGUE", specRestriction = 261, addedBySpec = 261 },
                { type = "spell", value = "Deathmark", category = "spec", classRestriction = "ROGUE", addedByClass = "ROGUE", specRestriction = 259, addedBySpec = 259 },
                { type = "spell", value = "Shadow Blades", category = "spec", classRestriction = "ROGUE", addedByClass = "ROGUE", specRestriction = 261, addedBySpec = 261 },
                { type = "spell", value = "Kingsbane", category = "spec", classRestriction = "ROGUE", addedByClass = "ROGUE", specRestriction = 259, addedBySpec = 259 },
                { type = "spell", value = "Power Infusion", category = "class", classRestriction = "PRIEST", addedByClass = "PRIEST" },
                { type = "spell", value = "Apotheosis", category = "spec", classRestriction = "PRIEST", addedByClass = "PRIEST", specRestriction = 257, addedBySpec = 257 },
                { type = "spell", value = "Dark Ascension", category = "spec", classRestriction = "PRIEST", addedByClass = "PRIEST", specRestriction = 258, addedBySpec = 258 },
                { type = "spell", value = "Void Eruption", category = "spec", classRestriction = "PRIEST", addedByClass = "PRIEST", specRestriction = 258, addedBySpec = 258 },
                { type = "spell", value = "Mindbender", category = "class", classRestriction = "PRIEST", addedByClass = "PRIEST" },
                { type = "spell", value = "Dark Command", category = "class", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT" },
                { type = "spell", value = "Pillar of Frost", category = "spec", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT", specRestriction = 251, addedBySpec = 251 },
                { type = "spell", value = "Unholy Assault", category = "spec", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT", specRestriction = 252, addedBySpec = 252 },
                { type = "spell", value = "Summon Gargoyle", category = "spec", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT", specRestriction = 252, addedBySpec = 252 },
                { type = "spell", value = "Empower Rune Weapon", category = "spec", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT", specRestriction = 251, addedBySpec = 251 },
                { type = "spell", value = "Bloodlust", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Ascendance", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Feral Spirit", category = "spec", classRestriction = "SHAMAN", addedByClass = "SHAMAN", specRestriction = 263, addedBySpec = 263 },
                { type = "spell", value = "Stormkeeper", category = "spec", classRestriction = "SHAMAN", addedByClass = "SHAMAN", specRestriction = 262, addedBySpec = 262 },
                { type = "spell", value = "Doom Winds", category = "spec", classRestriction = "SHAMAN", addedByClass = "SHAMAN", specRestriction = 263, addedBySpec = 263 },
                { type = "spell", value = "Combustion", category = "spec", classRestriction = "MAGE", addedByClass = "MAGE", specRestriction = 63, addedBySpec = 63 },
                { type = "spell", value = "Arcane Surge", category = "spec", classRestriction = "MAGE", addedByClass = "MAGE", specRestriction = 62, addedBySpec = 62 },
                { type = "spell", value = "Icy Veins", category = "spec", classRestriction = "MAGE", addedByClass = "MAGE", specRestriction = 64, addedBySpec = 64 },
                { type = "spell", value = "Time Warp", category = "class", classRestriction = "MAGE", addedByClass = "MAGE" },
                { type = "spell", value = "Summon Infernal", category = "spec", classRestriction = "WARLOCK", addedByClass = "WARLOCK", specRestriction = 267, addedBySpec = 267 },
                { type = "spell", value = "Summon Darkglare", category = "spec", classRestriction = "WARLOCK", addedByClass = "WARLOCK", specRestriction = 265, addedBySpec = 265 },
                { type = "spell", value = "Summon Demonic Tyrant", category = "spec", classRestriction = "WARLOCK", addedByClass = "WARLOCK", specRestriction = 266, addedBySpec = 266 },
                { type = "spell", value = "Dark Soul", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Provoke", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Invoke Xuen, the White Tiger", category = "spec", classRestriction = "MONK", addedByClass = "MONK", specRestriction = 269, addedBySpec = 269 },
                { type = "spell", value = "Invoke Yu'lon, the Jade Serpent", category = "spec", classRestriction = "MONK", addedByClass = "MONK", specRestriction = 270, addedBySpec = 270 },
                { type = "spell", value = "Invoke Niuzao, the Black Ox", category = "spec", classRestriction = "MONK", addedByClass = "MONK", specRestriction = 268, addedBySpec = 268 },
                { type = "spell", value = "Storm, Earth, and Fire", category = "spec", classRestriction = "MONK", addedByClass = "MONK", specRestriction = 269, addedBySpec = 269 },
                { type = "spell", value = "Growl", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Berserk", category = "spec", classRestriction = "DRUID", addedByClass = "DRUID", specRestriction = 103, addedBySpec = 103 },
                { type = "spell", value = "Berserk", category = "spec", classRestriction = "DRUID", addedByClass = "DRUID", specRestriction = 104, addedBySpec = 104 },
                { type = "spell", value = "Celestial Alignment", category = "spec", classRestriction = "DRUID", addedByClass = "DRUID", specRestriction = 102, addedBySpec = 102 },
                { type = "spell", value = "Convoke the Spirits", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Incarnation: Tree of Life", category = "spec", classRestriction = "DRUID", addedByClass = "DRUID", specRestriction = 105, addedBySpec = 105 },
                { type = "spell", value = "Incarnation: Guardian of Ursoc", category = "spec", classRestriction = "DRUID", addedByClass = "DRUID", specRestriction = 104, addedBySpec = 104 },
                { type = "spell", value = "Incarnation: Chosen of Elune", category = "spec", classRestriction = "DRUID", addedByClass = "DRUID", specRestriction = 102, addedBySpec = 102 },
                { type = "spell", value = "Torment", category = "class", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER" },
                { type = "spell", value = "Metamorphosis", category = "spec", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER", specRestriction = 577, addedBySpec = 577 },
                { type = "spell", value = "Dragonrage", category = "spec", classRestriction = "EVOKER", addedByClass = "EVOKER", specRestriction = 1467, addedBySpec = 1467 },
                { type = "spell", value = "Fury of the Aspects", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
            },
            [4] = {
                conflictStrategy = "sequence",
                { type = "action", value = 136, name = "Override Bar Button 4", conditions = "[overridebar]", category = "global", exclusive = true },
                { type = "action", value = 148, name = "Possess Bar Button 4", conditions = "[possessbar]", category = "global", exclusive = true },
                { type = "spell", value = "Bronze Timelock", conditions = "[flying]", category = "global", exclusive = true },
                { type = "spell", value = "Shockwave", category = "spec", classRestriction = "WARRIOR", addedByClass = "WARRIOR", specRestriction = 73, addedBySpec = 73 },
                { type = "spell", value = "Intimidating Shout", category = "class", classRestriction = "WARRIOR", addedByClass = "WARRIOR" },
                { type = "spell", value = "Blinding Light", category = "class", classRestriction = "PALADIN", addedByClass = "PALADIN" },
                { type = "spell", value = "Binding Shot", category = "class", classRestriction = "HUNTER", addedByClass = "HUNTER" },
                { type = "spell", value = "Intimidation", category = "class", classRestriction = "HUNTER", addedByClass = "HUNTER" },
                { type = "spell", value = "Blind", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Gouge", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Psychic Scream", category = "class", classRestriction = "PRIEST", addedByClass = "PRIEST" },
                { type = "spell", value = "Psychic Terror", category = "class", classRestriction = "PRIEST", addedByClass = "PRIEST" },
                { type = "spell", value = "Asphyxiate", category = "class", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT" },
                { type = "spell", value = "Blinding Sleet", category = "class", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT" },
                { type = "spell", value = "Gorefiend's Grasp", category = "spec", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT", specRestriction = 250, addedBySpec = 250 },
                { type = "spell", value = "Capacitor Totem", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Thunderstorm", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Sundering", category = "spec", classRestriction = "SHAMAN", addedByClass = "SHAMAN", specRestriction = 263, addedBySpec = 263 },
                { type = "spell", value = "Dragon's Breath", category = "spec", classRestriction = "MAGE", addedByClass = "MAGE", specRestriction = 63, addedBySpec = 63 },
                { type = "spell", value = "Blast Wave", category = "class", classRestriction = "MAGE", addedByClass = "MAGE" },
                { type = "spell", value = "Shadowfury", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Howl of Terror", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Leg Sweep", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Ring of Peace", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Incapacitating Roar", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Ursol's Vortex", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Mighty Bash", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Chaos Nova", category = "spec", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER", specRestriction = 577, addedBySpec = 577 },
                { type = "spell", value = "Sigil of Silence", category = "class", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER" },
                { type = "spell", value = "Sigil of Misery", category = "class", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER" },
                { type = "spell", value = "Landslide", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
                { type = "spell", value = "Tail Swipe", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
                { type = "spell", value = "Wing Buffet", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
            },
            [5] = {
                conflictStrategy = "sequence",
                { type = "action", value = 137, name = "Override Bar Button 5", conditions = "[overridebar]", category = "global", exclusive = true },
                { type = "action", value = 149, name = "Possess Bar Button 5", conditions = "[possessbar]", category = "global", exclusive = true },
                { type = "spell", value = "Aerial Halt", conditions = "[flying]", category = "global", exclusive = true },
                { type = "spell", value = "Storm Bolt", category = "class", classRestriction = "WARRIOR", addedByClass = "WARRIOR" },
                { type = "spell", value = "Piercing Howl", category = "class", classRestriction = "WARRIOR", addedByClass = "WARRIOR" },
                { type = "spell", value = "Hammer of Justice", category = "class", classRestriction = "PALADIN", addedByClass = "PALADIN" },
                { type = "spell", value = "Repentance", category = "class", classRestriction = "PALADIN", addedByClass = "PALADIN" },
                { type = "spell", value = "Turn Evil", category = "class", classRestriction = "PALADIN", addedByClass = "PALADIN" },
                { type = "spell", value = "Freezing Trap", category = "class", classRestriction = "HUNTER", addedByClass = "HUNTER" },
                { type = "spell", value = "Tar Trap", category = "class", classRestriction = "HUNTER", addedByClass = "HUNTER" },
                { type = "spell", value = "Scare Beast", category = "class", classRestriction = "HUNTER", addedByClass = "HUNTER" },
                { type = "spell", value = "Kidney Shot", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Cheap Shot", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Sap", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Pistol Shot", category = "spec", classRestriction = "ROGUE", addedByClass = "ROGUE", specRestriction = 260, addedBySpec = 260 },
                { type = "spell", value = "Shackle Undead", category = "class", classRestriction = "PRIEST", addedByClass = "PRIEST" },
                { type = "spell", value = "Mind Control", category = "class", classRestriction = "PRIEST", addedByClass = "PRIEST" },
                { type = "spell", value = "Holy Word: Chastise", category = "spec", classRestriction = "PRIEST", addedByClass = "PRIEST", specRestriction = 257, addedBySpec = 257 },
                { type = "spell", value = "Death Grip", category = "class", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT" },
                { type = "spell", value = "Chains of Ice", category = "class", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT" },
                { type = "spell", value = "Hex", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Earthgrab Totem", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Polymorph", category = "class", classRestriction = "MAGE", addedByClass = "MAGE" },
                { type = "spell", value = "Frost Nova", category = "class", classRestriction = "MAGE", addedByClass = "MAGE" },
                { type = "spell", value = "Ring of Frost", category = "class", classRestriction = "MAGE", addedByClass = "MAGE" },
                { type = "spell", value = "Fear", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Banish", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Seduction", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Paralysis", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Disable", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Entangling Roots", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Cyclone", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Hibernate", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Mass Entanglement", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Imprison", category = "class", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER" },
                { type = "spell", value = "Sleep Walk", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
                { type = "spell", value = "Oppressing Roar", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
            },
            [6] = {
                conflictStrategy = "sequence",
                { type = "action", value = 138, name = "Override Bar Button 6", conditions = "[overridebar]", category = "global", exclusive = true },
                { type = "action", value = 150, name = "Possess Bar Button 6", conditions = "[possessbar]", category = "global", exclusive = true },
                { type = "spell", value = "Second Wind", conditions = "[flying]", category = "global", exclusive = true },
                { type = "spell", value = "Charge", category = "class", classRestriction = "WARRIOR", addedByClass = "WARRIOR" },
                { type = "spell", value = "Heroic Leap", category = "class", classRestriction = "WARRIOR", addedByClass = "WARRIOR" },
                { type = "spell", value = "Intervene", category = "class", classRestriction = "WARRIOR", addedByClass = "WARRIOR" },
                { type = "spell", value = "Divine Steed", category = "class", classRestriction = "PALADIN", addedByClass = "PALADIN" },
                { type = "spell", value = "Disengage", category = "class", classRestriction = "HUNTER", addedByClass = "HUNTER" },
                { type = "spell", value = "Aspect of the Cheetah", category = "class", classRestriction = "HUNTER", addedByClass = "HUNTER" },
                { type = "spell", value = "Harpoon", category = "spec", classRestriction = "HUNTER", addedByClass = "HUNTER", specRestriction = 255, addedBySpec = 255 },
                { type = "spell", value = "Sprint", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Shadowstep", category = "class", classRestriction = "ROGUE", addedByClass = "ROGUE" },
                { type = "spell", value = "Grappling Hook", category = "spec", classRestriction = "ROGUE", addedByClass = "ROGUE", specRestriction = 260, addedBySpec = 260 },
                { type = "spell", value = "Leap of Faith", category = "class", classRestriction = "PRIEST", addedByClass = "PRIEST" },
                { type = "spell", value = "Angelic Feather", category = "class", classRestriction = "PRIEST", addedByClass = "PRIEST" },
                { type = "spell", value = "Death's Advance", category = "class", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT" },
                { type = "spell", value = "Wraith Walk", category = "class", classRestriction = "DEATHKNIGHT", addedByClass = "DEATHKNIGHT" },
                { type = "spell", value = "Ghost Wolf", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Spirit Walk", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Gust of Wind", category = "class", classRestriction = "SHAMAN", addedByClass = "SHAMAN" },
                { type = "spell", value = "Blink", category = "class", classRestriction = "MAGE", addedByClass = "MAGE" },
                { type = "spell", value = "Shimmer", category = "class", classRestriction = "MAGE", addedByClass = "MAGE" },
                { type = "spell", value = "Demonic Circle: Teleport", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Demonic Gateway", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Burning Rush", category = "class", classRestriction = "WARLOCK", addedByClass = "WARLOCK" },
                { type = "spell", value = "Roll", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Chi Torpedo", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Transcendence: Transfer", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Tiger's Lust", category = "class", classRestriction = "MONK", addedByClass = "MONK" },
                { type = "spell", value = "Dash", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Stampeding Roar", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Wild Charge", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Tiger Dash", category = "class", classRestriction = "DRUID", addedByClass = "DRUID" },
                { type = "spell", value = "Fel Rush", category = "spec", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER", specRestriction = 577, addedBySpec = 577 },
                { type = "spell", value = "Infernal Strike", category = "spec", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER", specRestriction = 581, addedBySpec = 581 },
                { type = "spell", value = "Vengeful Retreat", category = "spec", classRestriction = "DEMONHUNTER", addedByClass = "DEMONHUNTER", specRestriction = 577, addedBySpec = 577 },
                { type = "spell", value = "Hover", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
                { type = "spell", value = "Rescue", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
                { type = "spell", value = "Deep Breath", category = "class", classRestriction = "EVOKER", addedByClass = "EVOKER" },
            },
            [7] = {
                conflictStrategy = "sequence",
                { type = "action", value = 139, name = "Override Bar Button 7", conditions = "[overridebar]", category = "global", exclusive = true },
                { type = "action", value = 151, name = "Possess Bar Button 7", conditions = "[possessbar]", category = "global", exclusive = true },
                { type = "item", value = 5512, category = "global" },
                { type = "item", value = 211880, category = "global" },
                { type = "item", value = 211878, category = "global" },
                { type = "item", value = 113509, category = "global" },
            },
            [8] = {
                conflictStrategy = "sequence",
                { type = "action", value = 140, name = "Override Bar Button 8", conditions = "[overridebar]", category = "global", exclusive = true },
                { type = "action", value = 152, name = "Possess Bar Button 8", conditions = "[possessbar]", category = "global", exclusive = true },
                { type = "item", value = 211879, category = "global" },
                { type = "item", value = 211881, category = "global" },
            },
            [9] = {
                conflictStrategy = "sequence",
                { type = "macro", value = "/userandom item:198230, item:198173, item:116139, item:122283, item:44934, item:64456, item:97919, item:104304, item:86568, item:112059", name = "Random Toy", icon = "Interface\\Icons\\INV_Misc_Toy_04", category = "global" },
            },
            [10] = {
                conflictStrategy = "sequence",
                { type = "macro", value = "/run C_MountJournal.SummonByID(0)", name = "Random Favorite Mount", icon = "Interface\\Icons\\MountJournalPortrait", category = "global" },
                { type = "spell", value = "Highland Drake", category = "global" },
                { type = "spell", value = "Cliffside Wylderdrake", category = "global" },
            },
            [11] = {
                conflictStrategy = "sequence",
                { type = "spell", value = "Renewed Proto-Drake", category = "global" },
                { type = "spell", value = "Windborne Velocidrake", category = "global" },
                { type = "spell", value = "Winding Slitherdrake", category = "global" },
                { type = "spell", value = "Flourishing Whimsydrake", category = "global" },
            },
            [12] = {
                conflictStrategy = "sequence",
                { type = "item", value = 6948, category = "global" },
                { type = "item", value = 140192, category = "global" },
                { type = "item", value = 110560, category = "global" },
            },
        }
    }
    return demoGroup
end
