local addonName, Wise = ...

function Wise:GetDemoBarGroup()
    local demoGroup = {
        isWiser = true,
        type = "line",
        lineOrientation = "horizontal",
        dynamic = true,
        anchor = {point = "CENTER", x = 0, y = 0},
        visibilitySettings = {},
        keybindSettings = {},
        actions = {
            [1] = {
                conflictStrategy = "sequence",
                { type = "action", value = 133, conditions = "[overridebar]", category = "global" },
                { type = "action", value = 121, conditions = "[possessbar]", category = "global" },
                { type = "spell", value = "Shield Wall", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Die by the Sword", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Enraged Regeneration", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Rallying Cry", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Spell Reflection", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Ignore Pain", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Divine Shield", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Ardent Defender", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Guardian of Ancient Kings", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Lay on Hands", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Aura Mastery", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Blessing of Protection", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Divine Protection", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Aspect of the Turtle", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Survival of the Fittest", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Exhilaration", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Evasion", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Cloak of Shadows", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Crimson Vial", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Vanish", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Feint", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Pain Suppression", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Guardian Spirit", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Desperate Prayer", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Power Word: Barrier", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Divine Hymn", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Dispersion", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Vampiric Embrace", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Power Word: Life", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Icebound Fortitude", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Anti-Magic Shell", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Vampiric Blood", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Dancing Rune Weapon", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Anti-Magic Zone", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Lichborne", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Astral Shift", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Spirit Link Totem", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Healing Tide Totem", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Ancestral Guidance", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Earth Elemental", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Ice Block", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Greater Invisibility", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Alter Time", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Prismatic Barrier", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Blazing Barrier", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Ice Barrier", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Mass Barrier", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Unending Resolve", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Dark Pact", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Mortal Coil", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Fortifying Brew", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Diffuse Magic", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Dampen Harm", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Revival", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Life Cocoon", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Zen Meditation", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Touch of Karma", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Survival Instincts", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Barkskin", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Frenzied Regeneration", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Tranquility", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Ironbark", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Renewal", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Blur", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Netherwalk", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Metamorphosis", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Fiery Brand", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Obsidian Scales", category = "class", classRestriction = "EVOKER" },
                { type = "spell", value = "Renewing Blaze", category = "class", classRestriction = "EVOKER" },
                { type = "spell", value = "Rewind", category = "class", classRestriction = "EVOKER" },
                { type = "spell", value = "Emerald Communion", category = "class", classRestriction = "EVOKER" },
                { type = "spell", value = "Rescue", category = "class", classRestriction = "EVOKER" },
                { type = "spell", value = "Zephyr", category = "class", classRestriction = "EVOKER" },
            },
            [2] = {
                conflictStrategy = "sequence",
                { type = "action", value = 134, conditions = "[overridebar]", category = "global" },
                { type = "action", value = 122, conditions = "[possessbar]", category = "global" },
                { type = "spell", value = "Pummel", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Rebuke", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Counter Shot", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Muzzle", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Kick", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Silence", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Mind Freeze", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Wind Shear", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Counterspell", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Spell Lock", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Spear Hand Strike", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Skull Bash", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Solar Beam", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Consume Magic", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Quell", category = "class", classRestriction = "EVOKER" },
            },
            [3] = {
                conflictStrategy = "sequence",
                { type = "action", value = 135, conditions = "[overridebar]", category = "global" },
                { type = "action", value = 123, conditions = "[possessbar]", category = "global" },
                { type = "spell", value = "Taunt", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Avatar", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Recklessness", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Colossus Smash", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Warbreaker", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Sweeping Strikes", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Hand of Reckoning", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Avenging Wrath", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Crusade", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Sentinel", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Bestial Wrath", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Trueshot", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Coordinated Assault", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Call of the Wild", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Adrenaline Rush", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Shadow Dance", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Deathmark", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Shadow Blades", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Kingsbane", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Power Infusion", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Apotheosis", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Dark Ascension", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Void Eruption", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Mindbender", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Dark Command", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Pillar of Frost", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Unholy Assault", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Summon Gargoyle", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Empower Rune Weapon", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Bloodlust", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Ascendance", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Feral Spirit", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Stormkeeper", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Doom Winds", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Combustion", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Arcane Surge", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Icy Veins", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Time Warp", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Summon Infernal", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Summon Darkglare", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Summon Demonic Tyrant", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Dark Soul", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Provoke", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Invoke Xuen, the White Tiger", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Invoke Yu'lon, the Jade Serpent", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Invoke Niuzao, the Black Ox", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Storm, Earth, and Fire", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Growl", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Berserk", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Celestial Alignment", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Convoke the Spirits", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Incarnation: Tree of Life", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Incarnation: Guardian of Ursoc", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Incarnation: Chosen of Elune", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Torment", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Metamorphosis", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Dragonrage", category = "class", classRestriction = "EVOKER" },
                { type = "spell", value = "Bloodlust", category = "class", classRestriction = "EVOKER" },
            },
            [4] = {
                conflictStrategy = "sequence",
                { type = "action", value = 136, conditions = "[overridebar]", category = "global" },
                { type = "action", value = 124, conditions = "[possessbar]", category = "global" },
                { type = "spell", value = "Shockwave", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Intimidating Shout", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Blinding Light", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Binding Shot", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Intimidation", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Blind", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Gouge", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Psychic Scream", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Psychic Terror", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Asphyxiate", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Blinding Sleet", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Gorefiend's Grasp", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Capacitor Totem", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Thunderstorm", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Sundering", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Dragon's Breath", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Blast Wave", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Shadowfury", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Howl of Terror", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Leg Sweep", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Ring of Peace", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Incapacitating Roar", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Ursol's Vortex", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Mighty Bash", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Chaos Nova", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Sigil of Silence", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Sigil of Misery", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Landslide", category = "class", classRestriction = "EVOKER" },
                { type = "spell", value = "Tail Swipe", category = "class", classRestriction = "EVOKER" },
                { type = "spell", value = "Wing Buffet", category = "class", classRestriction = "EVOKER" },
            },
            [5] = {
                conflictStrategy = "sequence",
                { type = "action", value = 137, conditions = "[overridebar]", category = "global" },
                { type = "action", value = 125, conditions = "[possessbar]", category = "global" },
                { type = "spell", value = "Storm Bolt", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Piercing Howl", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Hammer of Justice", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Repentance", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Turn Evil", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Freezing Trap", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Tar Trap", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Scare Beast", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Kidney Shot", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Cheap Shot", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Sap", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Pistol Shot", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Shackle Undead", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Mind Control", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Chastise", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Death Grip", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Chains of Ice", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Hex", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Earthgrab Totem", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Polymorph", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Frost Nova", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Ring of Frost", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Fear", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Banish", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Seduction", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Paralysis", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Disable", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Entangling Roots", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Cyclone", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Hibernate", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Mass Entanglement", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Imprison", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Sleep Walk", category = "class", classRestriction = "EVOKER" },
                { type = "spell", value = "Oppressing Roar", category = "class", classRestriction = "EVOKER" },
            },
            [6] = {
                conflictStrategy = "sequence",
                { type = "action", value = 138, conditions = "[overridebar]", category = "global" },
                { type = "action", value = 126, conditions = "[possessbar]", category = "global" },
                { type = "spell", value = "Charge", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Heroic Leap", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Intervene", category = "class", classRestriction = "WARRIOR" },
                { type = "spell", value = "Divine Steed", category = "class", classRestriction = "PALADIN" },
                { type = "spell", value = "Disengage", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Aspect of the Cheetah", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Harpoon", category = "class", classRestriction = "HUNTER" },
                { type = "spell", value = "Sprint", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Shadowstep", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Grappling Hook", category = "class", classRestriction = "ROGUE" },
                { type = "spell", value = "Leap of Faith", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Angelic Feather", category = "class", classRestriction = "PRIEST" },
                { type = "spell", value = "Death's Advance", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Wraith Walk", category = "class", classRestriction = "DEATHKNIGHT" },
                { type = "spell", value = "Ghost Wolf", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Spirit Walk", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Gust of Wind", category = "class", classRestriction = "SHAMAN" },
                { type = "spell", value = "Blink", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Shimmer", category = "class", classRestriction = "MAGE" },
                { type = "spell", value = "Demonic Circle: Teleport", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Demonic Gateway", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Burning Rush", category = "class", classRestriction = "WARLOCK" },
                { type = "spell", value = "Roll", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Chi Torpedo", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Transcendence: Transfer", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Tiger's Lust", category = "class", classRestriction = "MONK" },
                { type = "spell", value = "Dash", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Stampeding Roar", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Wild Charge", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Tiger Dash", category = "class", classRestriction = "DRUID" },
                { type = "spell", value = "Fel Rush", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Infernal Strike", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Vengeful Retreat", category = "class", classRestriction = "DEMONHUNTER" },
                { type = "spell", value = "Hover", category = "class", classRestriction = "EVOKER" },
                { type = "spell", value = "Rescue", category = "class", classRestriction = "EVOKER" },
                { type = "spell", value = "Deep Breath", category = "class", classRestriction = "EVOKER" },
            },
            [7] = {
                conflictStrategy = "sequence",
                { type = "action", value = 139, conditions = "[overridebar]", category = "global" },
                { type = "action", value = 127, conditions = "[possessbar]", category = "global" },
                { type = "item", value = 5512, category = "global" },
                { type = "item", value = 211880, category = "global" },
                { type = "item", value = 211878, category = "global" },
                { type = "item", value = 113509, category = "global" },
            },
            [8] = {
                conflictStrategy = "sequence",
                { type = "action", value = 140, conditions = "[overridebar]", category = "global" },
                { type = "action", value = 128, conditions = "[possessbar]", category = "global" },
                { type = "item", value = 211879, category = "global" },
                { type = "item", value = 211881, category = "global" },
            },
            [9] = {
                conflictStrategy = "random",
                { type = "toy", value = 198230, category = "global" },
                { type = "toy", value = 198173, category = "global" },
                { type = "toy", value = 116139, category = "global" },
                { type = "toy", value = 122283, category = "global" },
                { type = "toy", value = 44934, category = "global" },
                { type = "toy", value = 64456, category = "global" },
                { type = "toy", value = 97919, category = "global" },
                { type = "toy", value = 104304, category = "global" },
                { type = "toy", value = 86568, category = "global" },
                { type = "toy", value = 112059, category = "global" },
            },
            [10] = {
                conflictStrategy = "sequence",
                { type = "macro", value = "/run C_MountJournal.SummonByID(0)", name = "Random Favorite Mount", icon = "Interface\\Icons\\MountJournalPortrait", category = "global" },
                { type = "spell", value = "Highland Drake", category = "global" },
                { type = "spell", value = "Cliffside Wylderdrake", category = "global" },
            },
            [11] = {
                conflictStrategy = "sequence",
                { type = "macro", value = "/cast Grand Expedition Yak\n/cast Traveler's Tundra Mammoth", name = "Utility Mounts", icon = "Interface\\Icons\\INV_Mount_Mammoth_Black", category = "global" },
            },
            [12] = {
                conflictStrategy = "sequence",
                { type = "item", value = 6948, category = "global" },
                { type = "item", value = 140192, category = "global" },
                { type = "item", value = 110560, category = "global" },
            },
        }
    }
    return demoGroup
end
